# Generated by Django 5.0.1 on 2024-02-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0004_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Event',
        ),
    ]
