# Generated by Django 5.0.1 on 2024-02-25 04:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0009_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='baseball_app.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='baseball_app.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseball_app.stadium'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.DeleteModel(
            name='GameSchedule',
        ),
    ]
