# Generated by Django 5.0.1 on 2024-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0013_remove_event_start_remove_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
