# Generated by Django 5.0.1 on 2024-03-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0014_event_comment_event_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.AlterField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseball_app.team', verbose_name='ホームチーム'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='baseball_app.stadium', verbose_name='球場'),
        ),
    ]
