# Generated by Django 5.0.1 on 2024-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0018_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.AddField(
            model_name='event',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
