# Generated by Django 5.0.1 on 2024-02-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0006_event_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
