# Generated by Django 5.0.1 on 2024-04-21 16:19

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0016_event_comment_event_score'),
    ]

    operations = [
        migrations.AddField(
    model_name='event',
    name='user',
    field=models.IntegerField(default=1),  # ここでデフォルト値を指定
    preserve_default=False,
),
    ]
